#
# Â© 2025-present https://github.com/jcarnaxide
#

[versions]
compileSdk = "35"
minSdk = "24"
buildTools = "35.0.0"
appUpdate = "2.1.0"
gmsTasks = "18.4.0"

[libraries]
appUpdateKtx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdate" }
gmsTasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "gmsTasks" }

[plugins]
android-library = { id = "com.android.library", version = "8.6.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.0" }
undercouch-download = { id = "de.undercouch.download", version = "5.6.0" }
