#
# Â© 2025-present https://github.com/jcarnaxide
#

[versions]
compileSdk = "35"
minSdk = "24"
buildTools = "35.0.0"

[plugins]
android-library = { id = "com.android.library", version = "8.6.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.0" }
undercouch-download = { id = "de.undercouch.download", version = "5.6.0" }
